### ISSUE TITLE
Does SynthDet run on Unity 2019.4.4f1 Personal?

### ISSUE THREAD

**Issue by dza6549** [Unity-Technologies/SynthDet#15]
Hi

I'm on Win 10 with 2019.4.4f1 Personal.  I downloaded the zip file (not cloned by command line) and upgraded the Perception package to Preview 0.2.0 but I have a bunch of errors e.g. 

Failed to load 'ProjectSettings/EditorSettings.asset'. File may be corrupted or was serialized with a newer version of Unity.

and a 'Display 1 No cameras rendering' message in the Game view.

Do I need to use 2019.3? Do I also need to clone the package with the command line (e.g. not use the zip file)?

Please let me know if I can provide more info.

Thanks

**Comment by banannakn** [comment]
Did you also download the unity-perception packages (https://github.com/Unity-Technologies/com.unity.perception/tree/9504462fb4263e7df6fcfd55184f08b5cc4750bc) seperatley in that folder (it was somehow missing in my project)? I don't know whether this solves all the erros but this solved a lot of errors for me but I can't remember my Error Codes..

**Comment by re-cheid** [comment]
hey @dza6549 I had the same problem, I figured out that this repository uses git LFS for larger binaries, meaning that if you just download the ZIP from here you wont get the binaries.
You need to `git clone` this repository instead of zip-download.

**Comment by JonathanHUnity** [comment]
Make sure you call `git lfs update` after cloning the repository. Take a look at https://github.com/Unity-Technologies/SynthDet/blob/master/docs/Prerequisites.md#prerequisites for more detailed instructions, and let us know if you hit any more issues.
