### ISSUE TITLE
semantic mask label generation

### ISSUE THREAD

**Issue by HaiyiMei** [Unity-Technologies/SynthDet#34]
Hey! Great work there!
I have an issue that I want to generate masks for semantic segmentation image, and output labels like COCO dataset.
![image](https://user-images.githubusercontent.com/35397764/93959612-ae03fd80-fd8b-11ea-8dbf-86d15bbbcec7.png)

I only found how to generate mask photos like above, but cannot generate a proper json file which include the mask information. Can you guys demonstrate it for me? Many thanks to you~

**Comment by JonathanHUnity** [comment]
Perception does not support COCO yet, but it is under discussion. You can track this issue on the perception repo at https://github.com/Unity-Technologies/com.unity.perception/issues/80
