### ISSUE TITLE
SynthDet v/s Perception package

### ISSUE THREAD

**Issue by ezorfa** [Unity-Technologies/SynthDet#41]
Hi @
Why are SynthDet scripts so heavily loaded with the code, when we can directly use the `UnityEngine.Experimental.Perception.*`? Is SynthDet a precursor to Perception package?

I believe this tutorial achieves the same : https://github.com/Unity-Technologies/com.unity.perception/tree/master/com.unity.perception/Documentation~/Tutorial

Thanks!

**Comment by mkamalza** [comment]
Hi, 
SynthDet is an older custom project that uses the Perception engine. It was built based on an academic paper from Google Cloud AI:
https://arxiv.org/pdf/1902.09967.pdf

Thus, SynthDet does not use the new Randomization tools in the latest version of the Perception package, rather, it has a custom placement and randomization algorithm. SynthDet currently produces the best-performing datasets for grocery object detection. 

However, using the new Randomization tools and starting from the tutorial you linked, we have found that you can enhance your Randomizations enough (beyond what's included in the tutorial) to reach similar levels of model performance. We are currently experimenting with this approach.

Moving forward, the new approach based on Randomizers is our recommended way of using the Perception package for more efficient experimentation and extensibility.

**Comment by ezorfa** [comment]
@mkamalza Does it use the latest DOTS technique?

**Comment by sleal-unity** [comment]
Hello! The perception package does have to a few APIs that utilize some of Unity's DOTS. Here are two examples:
1. Numeric parameters and samplers have APIs that utilize jobs and the burst compiler to [increase sampling performance](https://github.com/Unity-Technologies/com.unity.perception/blob/master/com.unity.perception/Documentation~/Randomization/Parameters.md#improving-sampling-performance)
2. The Poisson disk sampling algorithm used by the foreground and background object placement randomizers used in the perception tutorial utilize burst + jobs to generate placement points efficiently.

**Comment by ezorfa** [comment]
@mkamalza @sleal-unity I think `SynthDet` also uses Unity's DOTS. I see that some classes have "IJobComponentSystem" implemented like LightRandomizer.

**Comment by mohammedayub44** [comment]
@mkamalza just checking since its been some time, are there any new updates to the tutorials that you talked about ? 

Thanks !

**Comment by mkamalza** [comment]
@mohammedayub44 You can have a look at the SynthDet V2 project which is currently on a branch:
https://github.com/Unity-Technologies/SynthDet/tree/SynthDet_V2_RandomizerBased/SynthDet_V2

This project uses the new Randomizers only, and can achieve very similar model training performance to the original SynthDet.
