### ISSUE TITLE
Torchserve hello

### ISSUE THREAD

**Issue by msaroufim** [Unity-Technologies/SynthDet#57]
Hi team, I noticed you use [torchserve to run inferences](https://github.com/Unity-Technologies/perception-synthdet-torchserve) 

I'm a maintainer on [torchserve](https://github.com/pytorch/serve)  and we're looking to showcase more how people are using torchserve. So I was wondering if you'd be open to us featuring your project in our repo? I'll send you a draft PR so you can review the wording. Your use case is very informative of how we need to manage our scale out story and work under harsh latency requirements. I've always joked to my friends that a slow game isn't considered a game.

The game dev + ML story is still fragmented today and I'm glad Unity is working so actively to make it saner, so please let me know if you have any feedback or features requests for torchserve so I can make your life easier

In general I'm a big fan of Unity, I've written tutorials about [ML agents](https://marksaroufim.medium.com/building-your-own-game-simulations-for-reinforcement-learning-with-unity-ml-agents-a-code-deep-e69a7bbc601e), [ECS](https://marksaroufim.medium.com/entity-component-system-is-all-you-need-884f972bd867) and have many Unity tutorials on Youtube https://www.youtube.com/user/marksaroufim/videos

**Comment by JonathanHUnity** [comment]
Hi Mark, Sounds perfect. I'll reach out via email. ❤️ your channel btw!
